services:
  backend-db:
    image: postgres:17
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network
    ports:
      - "5432:5432"

networks:
  backend-network:
    driver: bridge

volumes:
  postgres-data:
